---
name: pre-commit

on:  # yamllint disable-line rule:truthy
  push:
    branches: ['develop', 'master']
  pull_request:
    branches: ['develop', 'master']

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4.4.0
      - uses: pre-commit/action@v3.0.0
